#
#  ____  ____ _____         _
# |  _ \/ ___|_   _|_ _ ___| | __
# | |_) \___ \ | |/ _` / __| |/ /
# |  _ < ___) || | (_| \__ \   <
# |_| \_\____/ |_|\__,_|___/_|\_\
#
# @author 若水
name: RSTask
api: ["2.0.0"]
version: "1.8.5-SNAPSHOT"
main: com.task.RsTask
author: "若水"
load: POSTWORLD
softdepend:
 - AutoUpData

permissions:
 RSTask.command.rank:
  description: §d任务积分排行榜
  default: true
 RSTask.command.sh:
  description: §d保存手上的物品到ItemTag
  default: op
 RSTask.command.ic:
  description: §c创建任务
  default: op
 RSTask.command.del-task:
  description: §e删除任务
  default: op
 RSTask.command.reload-task:
  description: §c重新同步任务文件
  default: op
 RSTask.command.reward:
  description: §e悬赏任务
  default: true