#
#  ____  ____ _____         _
# |  _ \/ ___|_   _|_ _ ___| |
# | |_) \___ \ | |/ _` / | |/ /
# |  _ < ___) || | (_| \__ \   <
# |_| \_\____/ |_|\__,_|___/_|\_\
#
# @author 若水
name: RSTask
api: ["2.0.0"]
version: "1.8.5-SNAPSHOT"
main: com.task.RsTask
author: "若水"
load: POSTWORLD
softdepend:
 - AutoUpData

permissions:
 RSTask.command.rank:
  description: §dTask Points Leaderboard
  default: true
 RSTask.command.sh:
  description: §dSave the item in hand to ItemTag
  default: op
 RSTask.command.ic:
  description: §cCreate Task
  default: op
 RSTask.command.del-task:
  description: §eDelete Task
  default: op
 RSTask.command.reload-task:
  description: §cResynchronize Task Files
  default: op
 RSTask.command.reward:
  description: §eBounty Task
  default: true
